services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: idea_mkdocs
    environment:
      - WATCHDOG_USE_POLLING=true
    ports:
      - "9102:8000"
    volumes:
      - ../:/docs/mkdocs
      - ../mkdocs.yml:/docs/mkdocs.yml
    command: serve --dev-addr 0.0.0.0:8000